### ISSUE TITLE
No longer works on Magento 2.4.0

### ISSUE THREAD

**Issue by KhaledBinAmir** [sslcommerz/SSLCommerz-Magento#1]
Dear @prabalsslw,
Thanks for your nice work, today I have updated my Magento to version 2.4.0 and found it is not working, this extension prevents checkout page loading.

Error:
`Deprecated Functionality: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /var/www/html/magento/app/code/Sslwireless/Sslcommerz/Model/Sslcommerz.php on line 176 [] []`

Please fix this as soon as you can. 

Can you also make some extra workouts?

- Option to disable auto-order cancelation when the user canceled the payment session.
- Option to choose EMI from the Checkout page and tenor limitations.
- Option to try pay again from customer dashboard.
- Option to Pay partial amount.

Thank you very much

**Comment by prabalsslw** [comment]
Hi,
This issue is occurring because of PHP version. We have resolved this issue in our last release, please use our latest module, do a fresh installation, upgrade & clear the cache. Hope you will not get this issue again.

* This is the default process, we treat the session out cycle as canceled. 
* For your kind information, EMI is not a default feature of SSLCommerz you have to avail this from SSLCommerz. You can get EMI settings option from SSLCommerz Merchant panel. If you want to implement `Emi with Parameter` where customers can select the tenure from the checkout page. Then you have develop the checkout page and need to pass `emi_option` & `emi_selected_inst` through our module. 
* SSLCommerz creates a unique session for each and every transaction. Once the session expired you can not pay for that session again. If the customer already canceled the transaction then he/she need to create the transaction again.
* There is no option for partial payment at SSLCommerz. SSLCommerz just processes the payment that you pass from your website. If you pass full payment then SSLCommerz process the full payment, if you pass partial payment then SSLCommerz will process partial payment. 

Thank You.

**Comment by hiimkhaled** [comment]
Thanks for the update
